service: serverlessSetup

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1

# functions
functions:
  hello:
    handler: src/functions/hello.handler
    events: # The events that trigger this function
      - http: 
          path: serverlessSetup/hello
          method: post


# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline

# Resources your functions use
resources:
  Resources:
    # SNS Topics
    SNSHelloEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Hello Event Topic
        TopicName: hello-event